spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
#spring.data.mongodb.uri=mongodb+srv://mohansid:Mongo123@cluster0.wnaenyl.mongodb.net/?appName=Cluster0
spring.data.mongodb.database = journalEntries
spring.data.mongodb.auto-index-creation=true
# spring.data.mongodb.username =
# spring.data.mongodb.password =